Feature/skeleton
DmitryOnopriienko/warehouse pull request #1
Opened 2023-08-31 14:40 UTC by DmitryOnopriienko

2023-09-01 14:08 UTC, ajax-shulepa-a approved these changes

2023-09-01 14:08 UTC, ajax-shulepa-a commented on src/main/kotlin/com/ajaxproject/warehouse/entity/Customer.kt
> +    var comment: String?)
) should be on a new line
file should end with an empty line
fix in all places

2023-09-01 14:09 UTC, ajax-shulepa-a requested changes
see comment (approved by mistake)

2023-09-01 15:23 UTC, DmitryOnopriienko commented on src/main/kotlin/com/ajaxproject/warehouse/entity/Customer.kt
> +    var comment: String?)
Fixed

2023-09-04 10:32 UTC, ajax-shulepa-a requested changes
files must end with an empty line (see knowledge sharing topic in tg)

2023-09-05 12:42 UTC, ajax-shulepa-a approved these changes

2023-09-05 14:42 UTC, merged