feature/migrate to gradle
DmitryOnopriienko/warehouse pull request #3
Opened 2023-09-07 14:07 UTC by DmitryOnopriienko

2023-09-07 21:47 UTC, ajax-gnatiuk-s requested changes

2023-09-07 21:47 UTC, ajax-gnatiuk-s commented on settings.gradle.kts
> + */
please clean up your gradle scripts from autogenerated redundant comments

2023-09-07 21:47 UTC, ajax-gnatiuk-s commented on build.gradle.kts
> +//}
please, clean up your script from commented code:
- uncomment
- or remove at all

TODO is the exception case :)

2023-09-08 10:46 UTC, ajax-shulepa-a approved these changes

2023-09-08 12:25 UTC, merged